// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igrzltfrmdfhnbekkkcx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlncnpsdGZybWRmaG5iZWtra2N4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNDUwNDcsImV4cCI6MjA2OTcyMTA0N30.oilPqUr1Rlgz8sPQJ4ERhxognPn22aWosaZ9aLA1zzI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});